### ISSUE TITLE
Deompile exception after updating to 1.5.605.12

### ISSUE THREAD

**Issue by derklaro** [MinecraftForge/ForgeFlower#122]
Commit 8af08ea6fd85ee3a2a7e826b5a238e9fa0cd7228 seems to introduce an exception when decompiling certain classes. One example of the stacktrace:
```
pool-1-thread-2: ERROR: Class net/minecraft/server/level/TicketType couldn't be fully decompiled.
java.lang.NullPointerException: Cannot invoke "org.jetbrains.java.decompiler.struct.StructClass.getMethods()" because "content" is null
	at org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent.getInferredExprType(InvocationExprent.java:361)
	at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.getCastedExprent(ExprProcessor.java:1067)
	at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.getCastedExprent(ExprProcessor.java:1040)
	at org.jetbrains.java.decompiler.main.ClassWriter.fieldToJava(ClassWriter.java:579)
	at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:268)
	at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:46)
	at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:175)
	at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:198)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zml2008** [comment]
@coehlrich

I think this only occurs when you have an incomplete classpath - several similar issues already exist in FF so I doubt this is urgent, but would be nice to fix the regression  if you have a spare moment
