### ISSUE TITLE
(21w13a) net.minecraft.world.level.levelgen.SimpleRandomSource.nextGaussian fails to decompile

### ISSUE THREAD

**Issue by zml2008** [MinecraftForge/ForgeFlower#89]
```
Method nextGaussian ()D in net/minecraft/world/level/levelgen/SimpleRandomSource couldn't be decompiled.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at org.jetbrains.java.decompiler.modules.decompiler.IfHelper.buildGraph(IfHelper.java:366)
        at org.jetbrains.java.decompiler.modules.decompiler.IfHelper.mergeIfs(IfHelper.java:72)
        at org.jetbrains.java.decompiler.modules.decompiler.SimplifyExprentsHelper.simplifyStackVarsStatement(SimplifyExprentsHelper.java:67)
        at org.jetbrains.java.decompiler.modules.decompiler.SimplifyExprentsHelper.simplifyStackVarsStatement(SimplifyExprentsHelper.java:65)
        at org.jetbrains.java.decompiler.modules.decompiler.SimplifyExprentsHelper.simplifyStackVarsStatement(SimplifyExprentsHelper.java:65)
        at org.jetbrains.java.decompiler.modules.decompiler.EliminateLoopsHelper.eliminateLoops(EliminateLoopsHelper.java:27)
        at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:157)
        at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:61)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:470)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:386)
        at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:149)
        at org.jetbrains.java.decompiler.struct.ContextUnit.save(ContextUnit.java:217)
        at org.jetbrains.java.decompiler.struct.StructContext.saveContext(StructContext.java:63)
        at org.jetbrains.java.decompiler.main.Fernflower.decompileContext(Fernflower.java:120)
        at org.spongepowered.gradle.vanilla.worker.JarDecompileWorker.execute(JarDecompileWorker.java:90)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
```

this came up when decompiling this week's snapshot. haven't had a chance to look into it further, can do so later.

**Comment by Geolykt** [comment]
I probably fixed it within https://github.com/Geolykt/ForgeFlower/commit/a9c2f7d6004316f702904a901f1d455e8b5544cb a while back, however I haven't PR'd that commit yet since I have yet to test it out in a minecraft environment.

**Comment by zml2008** [comment]
geo, did you look into any root causes of those exceptions, or just include stronger guards?

the exception still occurs after the recent rebase, so unfortunately upstream hasn't fixed it for us.

i'll take your commit for a spin, but it would be good to understand the root causes of the issues -- since clearly an assumption *somewhere* was wrong

**Comment by zml2008** [comment]
alright, tried it out -- my updated version is at https://github.com/MinecraftForge/ForgeFlower/compare/master...zml2008:fix-exceptions.

On MCPConfig 1.16.5, there were no changes to the output, and the `:1.16.5:testJdks` task passed.

In a 21w13a workspace, `SimpleRandomSource.nextGaussian()` now decompiles properly, with no other changes to output.

The resulting source is:
```java
   public double nextGaussian() {
      if (this.haveNextNextGaussian) {
         this.haveNextNextGaussian = false;
         return this.nextNextGaussian;
      } else {
         while(true) {
            double var0 = 2.0D * this.nextDouble() - 1.0D;
            double var2 = 2.0D * this.nextDouble() - 1.0D;
            double var4 = Mth.square(var0) + Mth.square(var2);
            if (!(var4 >= 1.0D)) {
               if (var4 != 0.0D) {
                  double var6 = Math.sqrt(-2.0D * Math.log(var4) / var4);
                  this.nextNextGaussian = var2 * var6;
                  this.haveNextNextGaussian = true;
                  return var0 * var6;
               }
            }
         }
      }
   }
```

For comparison, this is the same method decompiled in various other decompilers

CFR (0.151):
```java
    @Override
    public double nextGaussian() {
        double var2;
        double var0;
        double var4;
        if (this.haveNextNextGaussian) {
            this.haveNextNextGaussian = false;
            return this.nextNextGaussian;
        }
        do {
            var0 = 2.0 * this.nextDouble() - 1.0;
            var2 = 2.0 * this.nextDouble() - 1.0;
        } while ((var4 = Mth.square(var0) + Mth.square(var2)) >= 1.0 || var4 == 0.0);
        double var6 = Math.sqrt(-2.0 * Math.log(var4) / var4);
        this.nextNextGaussian = var2 * var6;
        this.haveNextNextGaussian = true;
        return var0 * var6;
    }
```

Procyon (0.5.36):
```java
    @Override
    public double nextGaussian() {
        if (this.haveNextNextGaussian) {
            this.haveNextNextGaussian = false;
            return this.nextNextGaussian;
        }
        double var4;
        double var5;
        double var6;
        do {
            var5 = 2.0 * this.nextDouble() - 1.0;
            var6 = 2.0 * this.nextDouble() - 1.0;
            var4 = Mth.square(var5) + Mth.square(var6);
        } while (var4 >= 1.0 || var4 == 0.0);
        final double var7 = Math.sqrt(-2.0 * Math.log(var4) / var4);
        this.nextNextGaussian = var6 * var7;
        this.haveNextNextGaussian = true;
        return var5 * var7;
    }
````

Fernflower (upstream, forge's build 403):
```java
    public double nextGaussian() {
        if (this.haveNextNextGaussian) {
            this.haveNextNextGaussian = false;
            return this.nextNextGaussian;
        } else {
            double var0;
            double var2;
            double var4;
            do {
                do {
                    var0 = 2.0D * this.nextDouble() - 1.0D;
                    var2 = 2.0D * this.nextDouble() - 1.0D;
                    var4 = Mth.square(var0) + Mth.square(var2);
                } while(var4 >= 1.0D);
            } while(var4 == 0.0D);

            double var6 = Math.sqrt(-2.0D * Math.log(var4) / var4);
            this.nextNextGaussian = var2 * var6;
            this.haveNextNextGaussian = true;
            return var0 * var6;
        }
    }
```


ForgeFlower treats the loop a bit strangely, but it appears to be correct.

**Comment by Geolykt** [comment]
I was unable to find any root causes (except for one NPE that I commented how it happens, but that is unrelated), however I haven't found any larger side effects to the modifications (compared to the code produced by other decompilers like Krakatau).
The good thing about that patch is that the only side effect is that it will only make broken code "working" by preventing a fatal exception to be thrown. So technically we could use that patch as a bandaid now (and creating log statements beforehand to make sure the future does not have any larger issues) and find the issues later.
The patch probably also belongs upstream, but I have no idea how jetbrain's monorepos behave, so I won't do that
